#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABi9J"
    "REFUWIW1l31Mm9cVh5/rD2xj42DsBRMICaPYWSLWLCUhTQdtuqIQ0lIyLUtHsrSLQrVl1ZZI"
    "6aRplaqtqqot07qObSpqNy2LomZdpVZpCunaKVqmiXZJJxQINB+lKgSDzYsxtvHHW/ze/WGz"
    "IAbGdNlPuv/c977nPveco3vOFYL/WXqgCCh/zFWw7w9KJABomflLmREBZhb8Wyw+zAI8Wb6b"
    "BFRL+E0Moh1fWC2f2r1ZhkDKOUMDVcILAuoEGOfb0WU72T0b1j4LbFjgW0UKntHgInD4vM1s"
    "dTRv4dNITNVDP/ARIDMHNALf0+CcBj8C3HMNZQNgU2Vx/XMHd7QDlXOm79DgNeBJ4Pz78OvR"
    "B2sVi8nASCT+iR0e0cE+HTxOet2s8iU8rcHTgC0XgBl/MDRZ7rJtf3JP3XHAAVRq8LaEsB7u"
    "10Hr3TBkqyyxJpMJfNH4DaAXeB94WQdtOnhYgpLxBkAb0JwLgDowrJwdVYJsXle2+/Faz4lx"
    "OKeDX+hhF3AecPxwz7av2k1GSyyWYCKSuDbPRgg4o4d6CZOZOX0qDVC4FIDs/WTij5eu3kym"
    "1CR19dUPfd9behH4HRDLrLnX7XLUCB1Mx+NcHpr81yK2BvRwt4RpYEwPJzNw2XMA+FgZnTxz"
    "Y2iUIrtFfrnhS9+4s2Ll86QTs2TvfdWNq8tKDULoGVLCAN1ZbA3qYb8OtgNvzU4uBSC/6Q8n"
    "hwbH8AUmxDpPlWzcdue3JfxTwgsDN4MPxXUWyDPjn0oEgJEstj4F3gA+nDtpWALAsnNa3e6/"
    "OcmNsnE81XexsrRc1qyvzDcXFO6xWfIYm4xKW1GeCEaTH3ArNDlrKQC3C8Z+MBJqbw2EDnZ/"
    "0OO5q+Fr1Dfvw2K1oWkpYuEp0f/3N7k2OjU/AXPSUiEY0cHXgZ9OBMP/8NbUa2ur1uH+nBO7"
    "JY8iWz6rSkrYtmsvLffX7gdKlwuwlAeCmVH2YMN96ytK3bpUaIy4Xo8QApBImT7FNm+JEzgI"
    "PLMcgKU8MKtSW77Z6fx8NatrHiARDRP1DxGfmsB5x0byXOWo0Sn213trlrP5cgCssUTSbHeV"
    "IHR6rGXrCPs+QhNGDFYHJZ4vorfaQeD4fwGgxiKoapL+/n56Bm4Qj07y8dAwPZcvE5uOk6lv"
    "y67uS+XALYCwIicDfqTUYS2wU9VwgEBERdU0goofXUolpaoL1/zbAGDd2nrMZLAV4tQbcbvd"
    "GPNMrEmlSCYTqKpK7aNP0a0cL6J7cFkAuYRA92JHx9bX/9q90ucfp7i4GKfTib3ARmHhCtxu"
    "N06nk+c7TrC9+REvsOV2A6wtLy//yuDgIKdPn5Z+v59wOPyfEY1GuX79Ou3t7ZhMJuN3n3ji"
    "sdsNsEYIsf7o0aP09fWJ/v5+FEUhEAgwPj7O8PAwp06doq2tjcrKSrFx48a6eXYLsxnPJQds"
    "09PTBR6PhyNHjuDz+TAYDKRSKWZmZohGo1RUVNDS0kIwGBSmPFMhYCddF1oAL1kup1wAJnw+"
    "n7Jq1SpXVVWVtNls4tq19LWvqioOh4MdO3YQiURkNBoVvb29w0C1PMcBNA6JJg5kM55LCHou"
    "XLjw2ytXrhAOh4XT6URRFEKhkAyHw5jy81GllNOxmHjn3XeUDmPHZfk2v0JyMNOD9WQzvtDN"
    "UQwEyHS1GVmAhkNtbd/yer11AwMDTk3TsJpMNG7axBqzmeOvvvq3k2fPfgcYAmplJycAvWhi"
    "EzC2GMD8EOyVXbwodtJIurGcVRw48/JLL70FFABWwAQ0tx479lyeppk9icQK4CpglF3ci+Ai"
    "kqtAIpsH5oZgn+zkNFAoO+kEPAusT5Hu5UaAQeBP7/X1vZvUpBaJxvzACuAwks2ikWNiJ6+Q"
    "7gMX1dwQbJVd/BkoA0CiiCZ2A++x2LMqrZXAo8CIPMchNAyiiV2kn2NLaq4HLgGv3ELDJTvp"
    "kl38BKgj7fq5MgPVQIO8QJn8C79HIyyaaM51c/jvJHTJLn4MHJ637iZwhXRzkpZkBYI1wIZM"
    "uv5cNPEsmXb7swIA5AMPyE5+BnhZrMBK0hVY8ppo4pekPZhczuaLAZAxbQG2yE5aEdxD+mk2"
    "u+2HwEWxk5PAAOnk/Ez6NzILVL2tTnOnAAAAAElFTkSuQmCC")
getIconData = Icon.GetData
getIconImage = Icon.GetImage
getIconBitmap = Icon.GetBitmap
getIconIcon = Icon.GetIcon

